### ISSUE TITLE
Incorrect rendering of menus

### ISSUE THREAD

**Issue by cunha** [fulhax/ncpamixer#29]
Hi, I am running Debian buster. I was experiencing https://github.com/fulhax/ncpamixer/issues/25, and compiling with `USE_WIDE=1` fixed part of the issue. However, menu options (accessed by pressing `c` in the default scheme) render incorrectly. Here is an example:

![ncpa](https://user-images.githubusercontent.com/325495/61839380-4f778280-ae5b-11e9-9369-285429a55a26.png)

Possibly relevant information:

```
[x1:~/bin]% ldd pamix
	linux-vdso.so.1 (0x00007ffc1b341000)
	libncursesw.so.6 => /lib/x86_64-linux-gnu/libncursesw.so.6 (0x00007fc10591a000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007fc1058ec000)
	libform.so.6 => /lib/x86_64-linux-gnu/libform.so.6 (0x00007fc1058d9000)
	libmenu.so.6 => /lib/x86_64-linux-gnu/libmenu.so.6 (0x00007fc1058ce000)
	libpulse.so.0 => /lib/x86_64-linux-gnu/libpulse.so.0 (0x00007fc10587a000)
...
[x1:~]% echo $TERM  # uxterm has the same problem
rxvt-unicode-256color # uxterm has the same problem
```

Any ideas?

**Comment by termgod** [comment]
On Void Linux it works correctly. I am also experiencing the same problem on Debian Buster. My terminal is st

**Comment by Juul** [comment]
Similar problem on Lubuntu 18.04.1 with `lxterminal`:

![pulse](https://user-images.githubusercontent.com/122752/73966763-8418cc00-48cb-11ea-9190-55fbf9135f2e.png)

**Comment by eylles** [comment]
same bug on ubuntu mate 19.10 across all terminal emulators, perhaps this bug is from the old ncurses present on debian based distros, as on ubuntu 19.10 the ncurses-bin version is 6.0+20151017 while arch packs version 6.2-1.

**Comment by cunha** [comment]
My guess was the opposite (that it was come incompatibility triggered by the upgrade to curses 6). Can you confirm it works correctly on Arch using 6.2? @termgod can you report what version of ncurses your binary is linked against on Void Linux?

Buster packs ncurses 6.1 and I do get the bug.

```
$ aptitude show libncursesw6
Package: libncursesw6                    
Version: 6.1+20181013-2+deb10u2
...
```

**Comment by eylles** [comment]
i cheked the void packages and void does pack 6.2, so we may assume whatever incompability introduced in curses 6 has been fixed in 6.2

**Comment by NickHastings** [comment]
I still see this issue using curses 6.2 on Debian bullseye. Specifically:
```
% ldd .local/bin/ncpamixer|grep curses
	libncursesw.so.6 => /lib/x86_64-linux-gnu/libncursesw.so.6 (0x00007f46bede7000)
	libncurses.so.6 => /lib/x86_64-linux-gnu/libncurses.so.6 (0x00007f46be949000)
% dpkg -S /lib/x86_64-linux-gnu/libncursesw.so.6 /lib/x86_64-linux-gnu/libncurses.so.6
libncursesw6:amd64: /lib/x86_64-linux-gnu/libncursesw.so.6
libncurses6:amd64: /lib/x86_64-linux-gnu/libncurses.so.6
% dpkg -l libncursesw6 libncurses6       
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version        Architecture Description
+++-==================-==============-============-===============================================================
ii  libncurses6:amd64  6.2+20201114-2 amd64        shared libraries for terminal handling
ii  libncursesw6:amd64 6.2+20201114-2 amd64        shared libraries for terminal handling (wide character support)
```
